### ISSUE TITLE
Removed sudo from line 126 now its working on Centos 6.6

### ISSUE THREAD

**Issue by JvGinkel** [aswen/nagios-plugins#12]
Hi,
I have remove the sudo from the line 126  https://github.com/aswen/nagios-plugins/blob/master/check_puppet_agent#L126

My version: 
<code>[ -z "${lastrunfile}" ] && lastrunfile=$(/usr/bin/puppet config print lastrunfile)
</code>

With sudo this command didn't work and $lastrunfile was empty. Now that I removed it the plugin works.

**Comment by mvisonneau** [comment]
Thanks, your alternative worked for me too on a Ubuntu 14.04 LTS

**Comment by aswen** [comment]
Hi, Excuse me for extremely late reply. Thanks for taking the time to report this issue. Since you reported this a lot is changed to this plugin but stille some sudo commands can't be avoided. So, a sudoline is required to allow the user that runs nrpe to execute _puppet config print_.
