### ISSUE TITLE
Not working through nrpe

### ISSUE THREAD

**Issue by igorgrin** [aswen/nagios-plugins#13]
It's not working for me for some reason.  I can execute the script fine on the client:
[root@dev003 ~]# /usr/lib64/nagios/plugins/check_puppet_agent
OK: Puppet agent "3.3.0" running catalogversion 1423524659, and executed at Mon 09 Feb 2015 04:24:53 PM PST for last time

But it won't work from the server using nrpe:
# /usr/lib64/nagios/plugins/check_nrpe -H dev003 -c check_puppet_agent
CRITICAL: Last run was 1423529323 seconds ago. crit is 7200

It looks like it's using puppet version as the last run time.  Both systems are CentOS-6

**Comment by mvisonneau** [comment]
I had the same problem on a Ubuntu 14.04.

Solved it by adding a rule into the sudoers file

```bash
nagios ALL=(root) NOPASSWD:/usr/bin/puppet config print *
```

But now I have an other problem, rights on file seems correct though :(

```
UNKNOWN: last_run_summary.yaml not found, not readable or incomplete 
```

**Comment by pebtron** [comment]
I'm seeing the same issues on RHEL 6.6. Quick and dirty solution is to have this in /etc/nrpe.d/check_puppet_agent.cfg:
command[check_puppet_agent]=/usr/bin/sudo /usr/lib64/nagios/plugins/check_puppet_agent

The root of the problem is that /var/lib/puppet is inaccessible to the nrpe user:
drwxr-x---.  11 puppet  puppet   4096 Dec 11 11:12 puppet

**Comment by aswen** [comment]
We use our own implementation of Puppet and we never noticed that. So, in our environment the nagios user running nrpe is allowed to read files in /var/lib/puppet/state. It's a world readable dir with some files that are open to read to everyone, some are not.
I suggest you change it this way as well. I prefer to minimize the amount of sudo commands in this script (prefer not to have them at all) and allowing nagios to read the last_run_summary.yaml file.
