### ISSUE TITLE
Socket timeout after 10 seconds

### ISSUE THREAD

**Issue by digitalprecision** [aswen/nagios-plugins#22]
Hi. I added your check_puppet_agent module to /usr/local/nagios/libexec, and gave it 755 perms with nagios.nagios ownership. 

When I run this command:

`/usr/local/nagios/libexec/j1n_check_puppet_agent -w 1800 -c 3600`

I get expected output, but when I run the following command I keep getting socket timeouts:

`/usr/local/nagios/libexec/check_nrpe -H service-a-2.sn1.vpc1.j1n.us -c check_local_puppet_agent`

Here is the excerpt from /usr/local/nagios/etc/nrpe.cfg:

`command[check_local_puppet_agent]=/usr/bin/sudo /usr/local/nagios/libexec/j1n_check_puppet_agent -w 1800 -c 3600`

And here is the sudo entry in /etc/sudoers:

`Cmnd_Alias PUPPETCHECK=/usr/bin/puppet config print runinterval,\
    /usr/bin/puppet config print splay,\
    /usr/bin/puppet config print splaylimit,\
    /usr/bin/puppet config print agent_disabled_lockfile,\
    /usr/bin/puppet config print lastrunfile,\
    /usr/bin/puppet config print pidfile, \
    /usr/local/nagios/libexec/j1n_check_puppet_agent
Defaults:nagios !requiretty
nagios ALL = NOPASSWD: PUPPETCHECK`

What am I missing?

**Comment by aswen** [comment]
Hi @digitalprecision,

However: the best chance is the following:
You've added `command[check_local_puppet_agent]=/usr/bin/sudo /usr/local/nagios/libexec/j1n_check_puppet_agent -w 1800 -c 3600` to your nrpe config

**Comment by digitalprecision** [comment]
I enabled debugging, and am seeing this in the log file:

`May  3 20:02:00 service-a-2.sn1.vpc1.j1n.us xinetd[18495]: START: nrpe pid=18500 from=::ffff:10.1.0.11
May  3 20:02:00 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: Added command[check_local_puppet_agent]=/usr/local/nagios/libexec/j1n_check_puppet_agent -w 1800 -c 3600
May  3 20:02:00 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: INFO: SSL/TLS initialized. All network traffic will be encrypted.
May  3 20:02:00 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: Handling the connection...
May  3 20:02:00 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: Host is asking for command 'check_local_puppet_agent' to be run...
May  3 20:02:00 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: Running command: /usr/local/nagios/libexec/j1n_check_puppet_agent -w 1800 -c 3600
May  3 20:02:10 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: Command completed with return code 2 and output: CRITICAL: Puppet daemon not running or something wrong with process
May  3 20:02:10 service-a-2.sn1.vpc1.j1n.us nrpe[18500]: Return Code: 2, Output: CRITICAL: Puppet daemon not running or something wrong with process
May  3 20:02:10 service-a-2.sn1.vpc1.j1n.us xinetd[18495]: EXIT: nrpe status=0 pid=18500 duration=10(sec)`

It's as if the exit code isn't being passed to the remote nagios server correctly...

**Comment by aswen** [comment]
Hi @digitalprecision ,

I guess you just managed to get the check running through nrpe. Now you've got a new possible problem but actually I'm not at all sure that the above is a problem that's caused by the check_puppet_agent plugin rather than nrpe config or so.
Can you check the following on your nagios server:
`/usr/local/nagios/libexec/check_nrpe -H service-a-2.sn1.vpc1.j1n.us -c check_local_puppet_agent;echo $?`
This should return 2 if Puppet isn't running.

**Comment by digitalprecision** [comment]
Found the issue. In my dev environment I don't run puppet agent on nodes b/c I don't want them picking up test changes unless I update them manually. However on the box I was testing, puppetmasterd was running. So it looks like there is an edge case where if puppemasterd is running but puppet agent is not, then the script just hangs.

**Comment by aswen** [comment]
Hi @digitalprecision,
Thanks for letting me know it works now. Can you please provide more info about the problem with the puppet check on puppetmasters? Then we can try to fix it for the future.
Thanks!

**Comment by aswen** [comment]
Oh, and please open a new issue for that. To keep the tracker clean.

Best regards,
Alex
