### ISSUE TITLE
Strict checks for either agent or master

### ISSUE THREAD

**Issue by digitalprecision** [aswen/nagios-plugins#23]
An edge case was discovered which was causing check_puppet_agent to hang. If a node was running puppetmasterd but not puppetd, then the check_puppet_agent script would hang indefinitely when run through nrpe. The quick fix would be to tighten the regex in line 233:

`ps axfww|egrep "/usr(/local)?/bin/ruby[^ ]* /usr(/local)?/s?bin/puppet(d)?$"|grep -v egrep`

I would suggest a more elegant approach, to allow us to pass -r Role. agent (default) or master. This way we can conditionally change the regex accordingly, yet still use the same script. The only difference would be to add a 2nd line to nrpe.cfg, something like:

```
command[check_local_puppet_agent]=/usr/local/nagios/libexec/j1n_check_puppet -w 1800 -c 3600
command[check_local_puppet_agent]=/usr/local/nagios/libexec/j1n_check_puppet -r master
```

**Comment by aswen** [comment]
Hi @digitalprecision,

Thanks very much for your clear explanation and the effort of reporting this.
I'd like to keep this check for the agent only, as the name suggests, and not add a puppetmasterd check. Reasons are that this check might look like a proper check for your master while no logic at all exists in the check and the only thing that's checked regarding the master would be if there's a process running with that name. That can be done with `check_procs` (provided by nagios_plugins).

So, shall we try to find out what happens to the check whenever a puppetmasterd process is running? I hardly doubt is fails on the check for the running process.
Can you run the script from the commandline on the masterserver to see where it hangs?
you might want to add `set -x` just before line 187 and `set +x` just before line 103. This gives a lot of output as it reveals all steps sh is doing while running.
I'm looking forward to the results.
Best  regards,
Alex

**Comment by digitalprecision** [comment]
I agree, check_progs would suffice for puppetmaster, but it would be cool to keep all puppet related logic in the same script. I will be submitting a pull request soon. You can close this out, the regex fixed the problem with puppetmaster and puppet running on same node.

**Comment by aswen** [comment]
cool
