### ISSUE TITLE
sudoers requested are not matching sudoers required

### ISSUE THREAD

**Issue by Rocco83** [aswen/nagios-plugins#42]
The plugin run one of:
https://github.com/aswen/nagios-plugins/blob/2455f72974a9d442ef2a4ef1e21466406693d1fc/check_puppet_agent#L224
https://github.com/aswen/nagios-plugins/blob/2455f72974a9d442ef2a4ef1e21466406693d1fc/check_puppet_agent#L227
https://github.com/aswen/nagios-plugins/blob/2455f72974a9d442ef2a4ef1e21466406693d1fc/check_puppet_agent#L230

As by:
https://github.com/aswen/nagios-plugins/blob/2455f72974a9d442ef2a4ef1e21466406693d1fc/check_puppet_agent#L234

While the sudoes requested https://github.com/aswen/nagios-plugins/blob/2455f72974a9d442ef2a4ef1e21466406693d1fc/check_puppet_agent#L41 does not include this command.

The result on nrpe is like:
`UNKNOWN: Internal error: Puppet version unknown from [1:31mError: Could not initialize global default settings: Permission denied @ dir_s_mkdir - /root/.puppetlabs[0m
`
As the requested sudoers are much more tailored, i would suggest to check the least privilege model before deciding if:
1) change sudoers requested
2) change the code to avoid the call

**Comment by aswen** [comment]
@Rocco83 Thanks for the detailed feedback!

Your proposal to decide between either changing sudoers or avoiding it would be simple if I knew a way to do all this without the need for sudo rights. Would you know a way to do that?

**Comment by Rocco83** [comment]
Unfortunately i do not know how to run it without sudo.
Maybe this can be done through an external run and saving the information "somewhere".
Or maybe that are already saved into lib directory.

But i was suggesting simply to fix the internal of the call, meaning, if we decide to call puppet config print all, this has to be mapped. currently there is instead a number of sudo profile.

I will show come code by pr in this days :)

**Comment by Rocco83** [comment]
Here we are, https://github.com/aswen/nagios-plugins/pull/43

**Comment by Rocco83** [comment]
As https://github.com/aswen/nagios-plugins/pull/43 is closed, this issue can be closed as well.
