### ISSUE TITLE
Ubuntu 18.04/16.04 and RHEL5 support broken

### ISSUE THREAD

**Issue by pebtron** [aswen/nagios-plugins#56]
As of commit 0dcd6910e0a6ce, associative arrays (available as of Bash version 4) are now a requirement for check_puppet_agent. That means Ubuntu 16.04/18.04 LTS, which link /bin/sh to /bin/dash, no longer function due to Dash not having associative array support. RHEL5 ships with Bash 3 which doesn't have associative array support so that broke too.

One option is to revert 0dcd6910e0a6ce. The commit doesn't add functionality from what I can tell, only an alternate style to accomplish the same thing.

Another option, and this fix is working for my Ubuntu 16.04/18.04 fleet, is to change the first #!/bin/sh to #!/bin/bash (assuming Bash is installed of course). This doesn't reconcile the Bash 4 requirement that older OS's such as RHEL5 don't have, though.

If it helps, I could submit a PR to change to /bin/bash and maybe add in a Bash version check or something. But I feel the best choice is to revert 0dcd6910e0a6ce if supporting older Bash versions is a priority.

-Paul

**Comment by aswen** [comment]
@pebtron Thanks for reporting this and doing that so complete. I tend to agree that reverting 0dcd691 keeps this plugin supported on more operating systems.
I will create a PR to revert #52.
